name: Run Python Script Every 12 Hours

on:
  schedule:
    # Menjalankan script setiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set environment variables from GitHub Secrets
      - name: Set Environment Variables
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DATA_JSON: ${{ secrets.DATA_JSON }}
        run: echo "Environment variables configured."

      # Run the Python script
      - name: Run Script
        run: python nh_claim.py
