name: AutoClaim Event

on:
  schedule:
    # Menjalankan setiap 3 jam
    - cron: "0 */3 * * *"

  workflow_dispatch: # Menjalankan manual jika diperlukan

jobs:
  auto-claim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests cloudscraper beautifulsoup4 python-dotenv

      - name: Run AutoClaim Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DATA_JSON: ${{ secrets.DATA_JSON }}
        run: python nh_claim.py
